#!/bin/bash
# Chronicle Seed — Bootstrap a minimal Chronicle instance
# Objective #8: Make Chronicle plantable
#
# What this does:
#   1. Creates data directory + SQLite schema
#   2. Pulls required Ollama models
#   3. Generates chronicle.env template
#   4. Creates systemd service files for the core loop
#   5. Prints what still needs manual setup
#
# Requirements:
#   - Linux with systemd (tested: Jetson AGX Orin, Ubuntu 22.04)
#   - Ollama installed and running
#   - Python 3.10+ with pip
#   - Internet access (for models + feeds)
#
# Usage:
#   chmod +x chronicle-seed.sh
#   ./chronicle-seed.sh [--data-dir DIR] [--bin-dir DIR] [--ollama-url URL]

set -euo pipefail

# Defaults
DATA_DIR="${HOME}/.homeforge-chronicle"
BIN_DIR="$(cd "$(dirname "$0")/.." && pwd)/bin"
OLLAMA_URL="http://localhost:11434"
DB_PATH="${DATA_DIR}/processed.db"

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --data-dir) DATA_DIR="$2"; shift 2 ;;
        --bin-dir) BIN_DIR="$2"; shift 2 ;;
        --ollama-url) OLLAMA_URL="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

DB_PATH="${DATA_DIR}/processed.db"

echo "=== Chronicle Seed ==="
echo "  Data dir:   ${DATA_DIR}"
echo "  Bin dir:    ${BIN_DIR}"
echo "  Ollama:     ${OLLAMA_URL}"
echo ""

# ─── Step 0: Prerequisites ─────────────────────────────────────────────

echo "[0/6] Checking prerequisites..."
MISSING=""
command -v python3 >/dev/null 2>&1 || MISSING="${MISSING} python3"
command -v sqlite3 >/dev/null 2>&1 || MISSING="${MISSING} sqlite3"
command -v curl >/dev/null 2>&1 || MISSING="${MISSING} curl"
command -v ollama >/dev/null 2>&1 || MISSING="${MISSING} ollama"

if [ -n "${MISSING}" ]; then
    echo "  ERROR: Missing required tools:${MISSING}"
    echo "  Install them before running this script."
    exit 1
fi

# Check core Python dep
if python3 -c "import requests" 2>/dev/null; then
    echo "  [ok] python3 + requests"
else
    echo "  [WARN] Python 'requests' not installed."
    echo "  Run: pip install -r $(dirname "$0")/requirements-core.txt"
fi
echo ""

# ─── Step 1: Data directory ───────────────────────────────────────────────

echo "[1/6] Creating data directory..."
mkdir -p "${DATA_DIR}"
echo "  Created: ${DATA_DIR}"

# ─── Step 2: Database schema ─────────────────────────────────────────────

if [ -f "${DB_PATH}" ]; then
    echo "[2/6] Database exists, skipping schema init."
else
    echo "[2/6] Initializing database..."
    SCHEMA_FILE="$(dirname "$0")/schema-seed.sql"
    if [ ! -f "${SCHEMA_FILE}" ]; then
        echo "  ERROR: ${SCHEMA_FILE} not found."
        echo "  Copy schema-seed.sql to the seed/ directory."
        exit 1
    fi
    sqlite3 "${DB_PATH}" < "${SCHEMA_FILE}"
    echo "  Database initialized: ${DB_PATH}"
fi

# ─── Step 3: Ollama models ───────────────────────────────────────────────

echo "[3/6] Checking Ollama models..."

check_model() {
    local model="$1"
    local desc="$2"
    if curl -sf "${OLLAMA_URL}/api/show" -d "{\"name\":\"${model}\"}" > /dev/null 2>&1; then
        echo "  [ok] ${model} (${desc})"
    elif curl -sf "${OLLAMA_URL}/api/pull" -d "{\"name\":\"${model}\",\"stream\":false}" > /dev/null 2>&1; then
        echo "  [ok] ${model} pulled"
    else
        echo "  [WARN] Failed to pull ${model} — pull manually: ollama pull ${model}"
    fi
}

# Minimal model set for seed Chronicle
check_model "qwen3-embedding:0.6b" "embeddings"
check_model "gemma4:26b" "classification gate (or substitute smaller model)"

# ─── Step 4: Environment config ──────────────────────────────────────────

ENV_FILE="${DATA_DIR}/chronicle.env"
if [ -f "${ENV_FILE}" ]; then
    echo "[4/6] chronicle.env exists, skipping."
else
    echo "[4/6] Creating chronicle.env template..."
    cat > "${ENV_FILE}" << ENVEOF
# Chronicle Environment — generated by chronicle-seed.sh
# Edit these values for your deployment.

# Data
CHRONICLE_DB=${DB_PATH}
CHRONICLE_BIN=${BIN_DIR}

# Ollama (local LLM inference)
CHRONICLE_OLLAMA_URL=${OLLAMA_URL}
CHRONICLE_EMBED_MODEL=qwen3-embedding:0.6b
CHRONICLE_GATE_MODEL=gemma4:26b

# Groq (cloud LLM for 32B+ models — optional, for deeper analysis)
# Get a key at https://console.groq.com
GROQ_API_KEY=

# ICP Canister (on-chain storage — optional for seed)
# CANISTER_ID=
# ICP_IDENTITY=

# Discord (alerts — optional)
# DISCORD_TOKEN=
# DISCORD_CHANNEL_ID=

# Nostr (publishing — optional)
# NOSTR_NSEC=

# MQTT (home awareness — optional)
# MQTT_BROKER=localhost
# MQTT_PORT=1883
ENVEOF
    echo "  Created: ${ENV_FILE}"
    echo "  EDIT THIS FILE before starting services."
fi

# ─── Step 5: Systemd services ────────────────────────────────────────────

echo "[5/6] Creating systemd service files..."

SERVICE_DIR="${HOME}/.config/systemd/user"
mkdir -p "${SERVICE_DIR}"

create_service() {
    local name="$1"
    local desc="$2"
    local script="$3"
    local restart_sec="${4:-30}"
    local svc_file="${SERVICE_DIR}/chronicle-${name}.service"

    if [ -f "${svc_file}" ]; then
        echo "  [exists] chronicle-${name}.service"
        return
    fi

    cat > "${svc_file}" << SVCEOF
[Unit]
Description=Chronicle ${desc}
After=network-online.target

[Service]
Type=simple
EnvironmentFile=${DATA_DIR}/chronicle.env
WorkingDirectory=${BIN_DIR}
ExecStart=/usr/bin/python3 ${BIN_DIR}/${script}
Restart=on-failure
RestartSec=${restart_sec}

[Install]
WantedBy=default.target
SVCEOF
    echo "  [created] chronicle-${name}.service"
}

# Core services (minimal seed)
create_service "feeds" "Feed Poller — Data Intake" "chronicle_feeds.py" 60
create_service "gemma" "Gate — Classification Router" "gemma.py" 30
create_service "sentinel" "Sentinel — Health Monitor" "chronicle_sentinel.py" 30
create_service "scribe" "Scribe — State Recorder" "chronicle_scribe.py" 10

# Knowledge layer (recommended)
create_service "intern" "Intern — Research Briefing" "intern.py" 30
create_service "crossref" "Crossref — Connection Discovery" "crossref.py" 30

# Home awareness (optional)
create_service "hal" "HAL — Home Awareness Layer" "chronicle_hal.py" 30

# Challenge layer (optional)
create_service "provocateur" "Provocateur — Challenge Poser" "provocateur.py" 60

systemctl --user daemon-reload 2>/dev/null || true

# ─── Step 6: Verify ────────────────────────────────────────────────────

echo "[6/6] Verifying installation..."
TABLE_COUNT=$(sqlite3 "${DB_PATH}" "SELECT count(*) FROM sqlite_master WHERE type='table'" 2>/dev/null || echo "0")
if [ "${TABLE_COUNT}" -ge 80 ]; then
    echo "  [ok] Database: ${TABLE_COUNT} tables"
else
    echo "  [WARN] Database has only ${TABLE_COUNT} tables (expected 87)"
fi
if [ -f "${ENV_FILE}" ]; then
    echo "  [ok] Environment: ${ENV_FILE}"
else
    echo "  [WARN] No environment file"
fi

echo ""
echo "=== Chronicle Seed Complete ==="
echo ""
echo "Next steps:"
echo "  1. Edit ${ENV_FILE}"
echo "     - Add GROQ_API_KEY if using cloud LLM"
echo "     - Configure optional integrations (Discord, Nostr, MQTT)"
echo ""
echo "  2. Start core services:"
echo "     systemctl --user enable --now chronicle-feeds"
echo "     systemctl --user enable --now chronicle-gemma"
echo "     systemctl --user enable --now chronicle-sentinel"
echo "     systemctl --user enable --now chronicle-scribe"
echo ""
echo "  3. Add knowledge layer when ready:"
echo "     systemctl --user enable --now chronicle-intern"
echo "     systemctl --user enable --now chronicle-crossref"
echo ""
echo "  4. Enable lingering (keeps services alive after logout):"
echo "     sudo loginctl enable-linger \$(whoami)"
echo ""
echo "  5. For ICP on-chain storage, set up dfx identity + canister"
echo "     See: https://internetcomputer.org/docs/current/developer-docs/"
echo ""
echo "  6. Verify installation:"
echo "     python3 $(dirname "$0")/seed-verify.py"
echo ""
echo "Minimal Chronicle: feeds + gemma + sentinel + scribe"
echo "Full Chronicle: + intern + crossref + provocateur + hal"
