// Tree Branch Crutch - 3D Printable
// Fits 2x2 lumber (actual 38.1mm), holds branches up to 3" (76mm)
// Generated by Chronicle

$fn = 48;

socket_inner = 39.1;
socket_outer = 49.1;
socket_depth = 65.0;
wall = 5.0;

cradle_w = 85.0;
cradle_h = 70.0;
cradle_wall = 5.0;
cradle_floor = 8.0;

total_w = cradle_w + 2 * cradle_wall;

notch_w = 3.0;
notch_d = 4.0;

screw_dia = 5.0;
screw_z = 20.0;

gusset_h = 30.0;

difference() {
    union() {
        // Socket - hollow square tube
        difference() {
            cube([socket_outer, socket_outer, socket_depth], center=false);
            translate([wall, wall, wall])
                cube([socket_inner, socket_inner, socket_depth], center=false);
        }

        // Cradle base plate
        translate([socket_outer/2 - total_w/2, 0, socket_depth])
            cube([total_w, socket_outer, cradle_floor], center=false);

        // Left cradle arm
        translate([socket_outer/2 - total_w/2, 0, socket_depth + cradle_floor])
            cube([cradle_wall, socket_outer, cradle_h], center=false);

        // Right cradle arm
        translate([socket_outer/2 + cradle_w/2, 0, socket_depth + cradle_floor])
            cube([cradle_wall, socket_outer, cradle_h], center=false);

        // Gussets (triangular supports from socket to cradle arms)
        // Left front gusset
        translate([socket_outer/2 - total_w/2, 0, socket_depth])
            rotate([90, 0, 90])
                linear_extrude(cradle_wall)
                    polygon([[0,0], [0, gusset_h], [socket_outer, 0]]);

        // Left back gusset
        translate([socket_outer/2 - total_w/2 + cradle_wall, socket_outer, socket_depth])
            rotate([90, 0, -90])
                linear_extrude(cradle_wall)
                    polygon([[0,0], [0, gusset_h], [socket_outer, 0]]);

        // Right front gusset
        translate([socket_outer/2 + cradle_w/2 + cradle_wall, 0, socket_depth])
            rotate([90, 0, 90])
                linear_extrude(cradle_wall)
                    polygon([[0,0], [0, gusset_h], [socket_outer, 0]]);

        // Right back gusset
        translate([socket_outer/2 + cradle_w/2, socket_outer, socket_depth])
            rotate([90, 0, -90])
                linear_extrude(cradle_wall)
                    polygon([[0,0], [0, gusset_h], [socket_outer, 0]]);

        // Inner cradle curve - rounded floor for branch comfort
        translate([socket_outer/2, socket_outer/2, socket_depth + cradle_floor])
            rotate([0, 0, 0])
                intersection() {
                    translate([-cradle_w/2, -socket_outer/2, 0])
                        cube([cradle_w, socket_outer, cradle_w/2]);
                    rotate([90, 0, 0])
                        cylinder(h=socket_outer, r=cradle_w/2, center=true);
                }
    }

    // Rope notches - V grooves on outside of each arm
    // Left arm notches
    for (frac = [0.35, 0.65]) {
        nz = socket_depth + cradle_floor + frac * cradle_h;

        // Front notch
        translate([socket_outer/2 - total_w/2 - 1, -1, nz - notch_w/2])
            cube([cradle_wall + 2, notch_d + 1, notch_w]);

        // Back notch
        translate([socket_outer/2 - total_w/2 - 1, socket_outer - notch_d, nz - notch_w/2])
            cube([cradle_wall + 2, notch_d + 1, notch_w]);
    }

    // Right arm notches
    for (frac = [0.35, 0.65]) {
        nz = socket_depth + cradle_floor + frac * cradle_h;

        translate([socket_outer/2 + cradle_w/2 - 1, -1, nz - notch_w/2])
            cube([cradle_wall + 2, notch_d + 1, notch_w]);

        translate([socket_outer/2 + cradle_w/2 - 1, socket_outer - notch_d, nz - notch_w/2])
            cube([cradle_wall + 2, notch_d + 1, notch_w]);
    }

    // Screw holes through socket walls (two axes)
    // Front-to-back
    translate([socket_outer/2, -1, screw_z])
        rotate([-90, 0, 0])
            cylinder(h=socket_outer + 2, d=screw_dia);

    // Left-to-right
    translate([-1, socket_outer/2, screw_z])
        rotate([0, 90, 0])
            cylinder(h=socket_outer + 2, d=screw_dia);

    // Top chamfer on cradle arms for comfort
    for (x = [socket_outer/2 - total_w/2, socket_outer/2 + cradle_w/2]) {
        translate([x, -1, socket_depth + cradle_floor + cradle_h - 2])
            rotate([0, 0, 0])
                translate([0, 0, 0])
                    cube([cradle_wall, socket_outer + 2, 3]);
    }
    // Replace with chamfered tops
}

// Re-add chamfered arm tops
module arm_top(x_pos) {
    translate([x_pos, 0, socket_depth + cradle_floor + cradle_h - 3])
        hull() {
            cube([cradle_wall, socket_outer, 0.01]);
            translate([cradle_wall * 0.15, 0, 3])
                cube([cradle_wall * 0.7, socket_outer, 0.01]);
        }
}

// Note: the chamfer in the difference above trims the tops.
// For a cleaner chamfer, use a slicer chamfer setting.
